### ISSUE TITLE
Using with angular cli

### ISSUE THREAD

**Issue by patrickoneill46** [Lightstreamer/Lightstreamer-example-StockList-client-angular2#2]
Hi,

I have noticed  a strange issue that if you run lightstreamer with an app created and served using the  angular cli.
In development mode i.e. `ng serve`, when you connect to a backend with lightstreamer by calling the `connect` function, after it has connected somehow the bootstrap application function (https://github.com/Lightstreamer/Lightstreamer-example-StockList-client-angular2/blob/master/src/app/main.ts#L15) gets triggered again.

Note, this does not happen when you run a production build and compile and minify the typescript source files.

I know this is an ask but could you guys investigate this? You could scaffold an app using the cli and re use everything you have here. I am seeing the same issue and I wonder is that why you have included a `tsc` task in your npm scripts.

**Comment by acarioni** [comment]
Hi Patrick,

Thanks for your feedback. I have update the project to reflect the configuration suggested by Angular 2 guidelines. Now the problem should have disappeared.

**Comment by patrickoneill46** [comment]
The problem is still there. I think it's a typescript issue. When I run a production build using the angular cli the problem disappears however, in development mode it still occurs. Could you guys build the existing app using angular cli to re product the error for yourselves?

**Comment by acarioni** [comment]
Hi Patrick,

My intent was to show a bare bones application integrating the Ligthstreamer client. 
I tried to convert the demo into a cli project but I had no success (I am not an expert Angular 2 developer so if you can suggest how to make the conversion, I’ll try to reproduce your problem).

**Comment by patrickoneill46** [comment]
If you just run 'ng init' using the cli and copy your files over it works fine. I want to see if you can re produce the issue

**Comment by acarioni** [comment]
I succeeded in converting and running the demo.
This is the output of ng serve:

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
** NG Live Development Server is running on http://localhost:4200. **
Hash: d196daeaf0c5f253ffbe
Time: 17365ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 228 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 9.31 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 11.5 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.28 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.

**Comment by patrickoneill46** [comment]
And when you run it with ng serve do you see in the (browser) console that the app is initialized again AFTER lightstreamer has connected?

**Comment by acarioni** [comment]
I don’t see a second initialization of the application (i.e. after the request http://localhost:8080/lightstreamer/create_session.js ).
I’m using Firefox 51 on Windows 10. 
Which browser do you use?

**Comment by patrickoneill46** [comment]
Can you copy and paste your console logs? How are you running the application?

**Comment by acarioni** [comment]
I have a suspect.
Try to remove the following lines from index.html:


<script src="systemjs.config.js"></script>
<script>
      System.import('main.js').catch(function(err){ console.error(err); });
    </script>
</head>

**Comment by patrickoneill46** [comment]
what version of the cli are you using? It should be running on webpack instead of system js now.

I am seeing `Angular is running in the development mode. Call enableProdMode() to enable the production mode.` on initialization, then again after Lightsteamer connects

**Comment by acarioni** [comment]
The cli uses Webpack but the demo, which was developed without the cli, is still using SystemJs. So you should remove the old imports from index.html to avoid the double initialization.

**Comment by patrickoneill46** [comment]
That doesn't address the problem. If you port the demo to an app created using the cli - do you see the error?

If you compile it and remove webpack the issue doesn't occur. The issue is running in a webpack development environment i.e. using the angular cli. Can you please try doing that to replicate the error?

**Comment by acarioni** [comment]
Launching the demo from a cli project I got:

_The resource from “http://localhost:4200/systemjs.config.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff).
ReferenceError: System is not defined
GET http://localhost:4200/sockjs-node/info?t=1487080950436
POST http://localhost:8080/lightstreamer/create_session.js_

Notwithstanding the error the application works fine.

**Comment by patrickoneill46** [comment]
Okay, you are using an old version of the cli. It was moved off system js and onto webpack in October. Using the latest version of the cli does the issue occur?

**Comment by acarioni** [comment]
After updating the cli I got
![image](https://cloud.githubusercontent.com/assets/18554100/22933537/2c2b8af8-f2cc-11e6-8cdf-1f1c30201855.png)

**Comment by patrickoneill46** [comment]
That's because you didn't update your index.html, I can see you are still using the one generated with old cli. Generate a new project with the cli, port your application typescript files over as they are and you will see the issue.

**Comment by acarioni** [comment]
I've done exactly as you said. I get no error and the app works fine. 
Running ng -v I get
_@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7_

**Comment by patrickoneill46** [comment]
Okay great, what version of Lightstreamer are you using.  The app works fine for me too, but I am using Lighstreamer js client version 6.x. And when it creates a session it causes the bootstrap app function to be run again.

**Comment by acarioni** [comment]
I'm using Lightstreamer Web Client  version 7.0.2 build 1710.

**Comment by acarioni** [comment]
This would be very strange since the application calls the client, but the client doesn't call the application.

**Comment by patrickoneill46** [comment]
I know it's really hard to track down. Can you downgrade your JS client version and see if the issue occurs? I am presently trying to get the Lighstreamer server upgraded so I can upgrade my client version but am stuck for now

**Comment by acarioni** [comment]
I have tried with version 6.1.4 build 1640.11 and I see no error.
The only line logged on the console is "GET http://localhost:4200/sockjs-node/info?t=1487087970633".

Can you send your log pointing out where you see the bootstrap called twice?

**Comment by patrickoneill46** [comment]
Running on ng serve I see this

`Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`

And then it is called again after lightstreamer has created the session

**Comment by acarioni** [comment]
When I run ng serve I don't see that message. I see instead "** NG Live Development Server is running on http://localhost:4200. **".

**Comment by patrickoneill46** [comment]
In the browser console i mean

**Comment by acarioni** [comment]
I have tried the same experiment using Chrome instead of Firefox. Now I see the message "Angular 2 is running in the development mode." but only one time.
If you attach your entire project, I'll try to debug on my machine.

**Comment by alireza267** [comment]
I have the same problem, however i see the problem(restarting the application on ls connection) in production mode too. I have my own application written in angular 6 and using lightstreamer v6 and v7.
I think this is an angular or a LightStreamer issue. the point is when i don't use this line :
```
    this.lsClient.connectionSharing.enableSharing(
      "SampleConnection",
      "ATTACH",
      "CREATE"
    );
```
my application restarts infinite times.

**Comment by alireza267** [comment]
Any answer? I need help. I've got a sample project that you can see this issue @acarioni

**Comment by acarioni** [comment]
Lightstreamer client library has no dependency whatsoever with Angular. So I see no way how the connection to the Lightstreamer server could possibly restart the application by itself. 

Have you verified that Angular components are wired correctly and that there is no uncaught exception?

**Comment by alireza267** [comment]
@acarioni thank you for your reply.
yes, I have. I think there is no exception related to angular components. angular components  are initialized normally until somewhere in code that tries to connect to lightStreamer server. This is where the problem emerges! At this point angular components and services are restarted.
I put a sample angular project on github  that shows the problem. You can click [here ](https://github.com/alireza267/lsConnectionTest)and run it by some simple steps: 

1. in LsConnection folder run  “npm install”

2. And run “ng serve -o”

3.Then you can see result in browser console( **“ngInit appComponent”** shows twice)

**Comment by acarioni** [comment]
It seems that the problem affects only the old Lightstreamer client library 6.0.x. The newer versions work just fine.
Please, update the client library to a recent version: if you have a Lightstreamer server 5.x, you can use the [client library 6.1.4](https://www.lightstreamer.com/repo/distros/Lightstreamer_Allegro-Presto-Vivace_5_1_2_Colosseo_20140722.zip%23/Lightstreamer/DOCS-SDKs/sdk_client_javascript/); if you have a newer server, you can find the client library in the server distribution folder under _DOCS-SDKs/sdk_client_web_unified_ or in the [download page](https://lightstreamer.com/download/) clicking on the button “Look Inside”.
